-- PASS_PRODUCT 테이블 생성
CREATE TABLE PASS_PRODUCT (
    prod_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '상품ID',
    sport_id BIGINT NOT NULL COMMENT '스포츠ID',
    prod_nm VARCHAR(100) NOT NULL COMMENT '상품명',
    prod_amt DECIMAL(15, 2) NOT NULL COMMENT '상품금액',
    prv_cnt INT NOT NULL COMMENT '제공횟수',
    use_yn BOOLEAN NOT NULL DEFAULT TRUE COMMENT '사용여부',
    reg_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    upd_dt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CONSTRAINT fk_pass_product_sport FOREIGN KEY (sport_id) REFERENCES SPORT_TYPE(sport_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='이용권상품';

